# @see https://bitbucket.org/j88per/laravel-docker/overview
# modified to use standard images and extensions
version: '3.4'

services:
  # extend / customized official php 7.3 image to include composer
  # can add other extensions
  php:
    build: ./docker/php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html:cached
      - /tmp:/tmp
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini

  # nginx w/ custom conf and ssl support
  nginx:
    image: nginx:1.15
    volumes:
      - ./:/var/www/html
      - /tmp:/tmp
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443

  # mysql for data persistence
  mysql:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /tmp:/tmp
    environment:
      - MYSQL_DATABASE=exercise
      - MYSQL_ROOT_PASSWORD=exercise

  # mysql for unit and integration tests
  mysql_test:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
      - 33070:33060
    environment:
      - MYSQL_DATABASE=exercise
      - MYSQL_ROOT_PASSWORD=exercise

  # redis for sessions
  redis:
    image: redis:4
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /tmp:/tmp
